---

- name: apt update 
  apt: update_cache=yes 
  changed_when: False
  when: ansible_os_family == "Debian"
  
- name: install general packages (Debian)
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ website_packages_general }}"
  when: ansible_os_family == "Debian"	

- name: install general packages (RHEL)
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ website_packages_general }}"
  when: ansible_os_family == "RedHat"
